In [8]:
import pandas_gbq
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


project_name = "social-computing-436902"
dataset_name = "stackexchange"
colors = plt.get_cmap('plasma').colors
quoted_table_name = lambda table_name:f"`{project_name}`.`{dataset_name}`.`{table_name}`"

In [2]:


# table top_one_percent_of_contributors was created using top_one_percent_of_contributors.sql

top_1pct_users_df = pandas_gbq.read_gbq(f"select * from {quoted_table_name('top_one_percent_of_contributors')}")

/home/prithaj/.virtualenvs/stackoverflow_analysis-1iOcKwg9/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2379: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(

In [3]:
top_1pct_users_df

,OwnerUserId,DisplayName,CreationDate,Reputation,AboutMe,QuestionsAnswered,PctRank
0,3850012,hvaughan3,2014-07-17 16:13:47.343,11055,<p>Working at Sogeti/Capgemini in the Dallas U...,310,0.995866
1,104427,Escualo,2009-05-10 17:31:59.413,41394,<p>I really like coding. My favorite languages...,309,0.995852
2,58508,Jimmy Bogard,2009-01-24 01:18:04.840,26425,"<p>.NET developer, and all around decent guy</...",297,0.995632
3,133190,regulus6633,2009-07-04 18:45:53.363,18936,<p>I'm a full-time lead engineer in the aerosp...,654,0.998383
4,210841,David Lazar,2009-11-14 00:44:23.747,11219,<p>I am a computer engineer. I am an expert de...,1042,0.999146
...,...,...,...,...,...,...,...
30924,592058,annoyingmouse,2011-01-27 10:59:26.707,5614,"<p>Dominic Myers here, I code PHP, JavaScript,...",195,0.992664
30925,2684660,asontu,2013-08-15 03:22:25.300,4578,"<p><strong><a href=""http://stackoverflow.com/q...",195,0.992664
30926,101827,Mike Atlas,2009-05-05 20:31:44.953,8243,"<p><a href=""http://about.me/mikeatlas"" rel=""no...",195,0.992664
30927,1197411,Jack P.,2012-02-08 14:27:15.410,11497,"<p>.NET (F#/C#), C, C++, Python developer work...",195,0.992664
30928,1145578,soyuka,2012-01-12 13:14:01.803,8975,None,195,0.992664

In [6]:
with open("bigquery_sql/questions_answered_distribution.sql", "r") as f:
    questions_answered_sql = f.read()

questions_answered_df = pandas_gbq.read_gbq(questions_answered_sql)

/home/prithaj/.virtualenvs/stackoverflow_analysis-1iOcKwg9/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2379: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(

In [7]:
questions_answered_df

         OwnerUserId  num_questions_answered
0             436641                    1064
1             703016                     471
2            1289716                     432
3            1105376                     673
4             755645                    1021
...              ...                     ...
3103374      4588272                      16
3103375      6420563                      16
3103376     13168322                      16
3103377     11701915                      16
3103378      5402974                      16

[3103379 rows x 2 columns]

In [11]:
with plt.style.context("Solarize_Light2"):
    sns.histplot(data=questions_answered_df, x="num_questions_answered", kde=True, alpha=0.5)
    plt.legend(loc="upper right")
    # plt.xlim(0,3_000_000)
    plt.tight_layout()
    plt.title("Distribution of number of questions answered on StackOverflow", fontdict={"size":10})
    plt.show()